create table "public"."ingredient_available_units" (
    "ingredient_id" bigint generated by default as identity not null,
    "available_unit" text not null,
    "conversion_rate" bigint not null
);


alter table "public"."ingredient_available_units" enable row level security;

create table "public"."ingredients" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "reference_unit" text not null,
    "created_at" timestamp without time zone default now()
);


alter table "public"."ingredients" enable row level security;

create table "public"."instructions" (
    "recipe_id" bigint generated by default as identity not null,
    "content" text not null,
    "index" bigint not null
);


alter table "public"."instructions" enable row level security;

create table "public"."planning_ingredients_in_stock" (
    "planning_id" bigint generated by default as identity not null,
    "ingredient_id" bigint generated by default as identity not null,
    "amount" bigint not null
);


alter table "public"."planning_ingredients_in_stock" enable row level security;

create table "public"."planning_ingredients_obtained" (
    "planning_id" bigint generated by default as identity not null,
    "ingredient_id" bigint generated by default as identity not null
);


alter table "public"."planning_ingredients_obtained" enable row level security;

create table "public"."planning_recipes" (
    "planning_id" bigint generated by default as identity not null,
    "recipe_id" bigint generated by default as identity not null,
    "portions" bigint not null
);


alter table "public"."planning_recipes" enable row level security;

create table "public"."plannings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."plannings" enable row level security;

create table "public"."recipe_ingredients" (
    "recipe_id" bigint not null,
    "ingredient_id" bigint not null,
    "amount" bigint not null,
    "unit" text not null
);


alter table "public"."recipe_ingredients" enable row level security;

create table "public"."recipes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "description" text,
    "image_url" text
);


alter table "public"."recipes" enable row level security;

CREATE UNIQUE INDEX ingredient_available_unit_pkey ON public.ingredient_available_units USING btree (ingredient_id);

CREATE UNIQUE INDEX ingredients_pkey ON public.ingredients USING btree (id);

CREATE UNIQUE INDEX instructions_pkey ON public.instructions USING btree (recipe_id);

CREATE UNIQUE INDEX planning_ingredients_in_stock_pkey ON public.planning_ingredients_in_stock USING btree (planning_id, ingredient_id);

CREATE UNIQUE INDEX planning_ingredients_obtained_pkey ON public.planning_ingredients_obtained USING btree (planning_id, ingredient_id);

CREATE UNIQUE INDEX planning_recipes_pkey ON public.planning_recipes USING btree (planning_id, recipe_id);

CREATE UNIQUE INDEX plannings_pkey ON public.plannings USING btree (id);

CREATE UNIQUE INDEX recipe_ingredients_pkey ON public.recipe_ingredients USING btree (recipe_id, ingredient_id);

CREATE UNIQUE INDEX recipes_pkey ON public.recipes USING btree (id);

alter table "public"."ingredient_available_units" add constraint "ingredient_available_unit_pkey" PRIMARY KEY using index "ingredient_available_unit_pkey";

alter table "public"."ingredients" add constraint "ingredients_pkey" PRIMARY KEY using index "ingredients_pkey";

alter table "public"."instructions" add constraint "instructions_pkey" PRIMARY KEY using index "instructions_pkey";

alter table "public"."planning_ingredients_in_stock" add constraint "planning_ingredients_in_stock_pkey" PRIMARY KEY using index "planning_ingredients_in_stock_pkey";

alter table "public"."planning_ingredients_obtained" add constraint "planning_ingredients_obtained_pkey" PRIMARY KEY using index "planning_ingredients_obtained_pkey";

alter table "public"."planning_recipes" add constraint "planning_recipes_pkey" PRIMARY KEY using index "planning_recipes_pkey";

alter table "public"."plannings" add constraint "plannings_pkey" PRIMARY KEY using index "plannings_pkey";

alter table "public"."recipe_ingredients" add constraint "recipe_ingredients_pkey" PRIMARY KEY using index "recipe_ingredients_pkey";

alter table "public"."recipes" add constraint "recipes_pkey" PRIMARY KEY using index "recipes_pkey";

alter table "public"."ingredient_available_units" add constraint "ingredient_available_unit_ingredient_id_fkey" FOREIGN KEY (ingredient_id) REFERENCES ingredients(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."ingredient_available_units" validate constraint "ingredient_available_unit_ingredient_id_fkey";

alter table "public"."instructions" add constraint "instructions_recipe_id_fkey" FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."instructions" validate constraint "instructions_recipe_id_fkey";

alter table "public"."planning_ingredients_in_stock" add constraint "planning_ingredients_in_stock_ingredient_id_fkey" FOREIGN KEY (ingredient_id) REFERENCES ingredients(id) not valid;

alter table "public"."planning_ingredients_in_stock" validate constraint "planning_ingredients_in_stock_ingredient_id_fkey";

alter table "public"."planning_ingredients_in_stock" add constraint "planning_ingredients_in_stock_planning_id_fkey" FOREIGN KEY (planning_id) REFERENCES plannings(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."planning_ingredients_in_stock" validate constraint "planning_ingredients_in_stock_planning_id_fkey";

alter table "public"."planning_ingredients_obtained" add constraint "planning_ingredients_obtained_ingredient_id_fkey" FOREIGN KEY (ingredient_id) REFERENCES ingredients(id) not valid;

alter table "public"."planning_ingredients_obtained" validate constraint "planning_ingredients_obtained_ingredient_id_fkey";

alter table "public"."planning_ingredients_obtained" add constraint "planning_ingredients_obtained_planning_id_fkey" FOREIGN KEY (planning_id) REFERENCES plannings(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."planning_ingredients_obtained" validate constraint "planning_ingredients_obtained_planning_id_fkey";

alter table "public"."planning_recipes" add constraint "planning_recipes_planning_id_fkey" FOREIGN KEY (planning_id) REFERENCES plannings(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."planning_recipes" validate constraint "planning_recipes_planning_id_fkey";

alter table "public"."planning_recipes" add constraint "planning_recipes_recipe_id_fkey" FOREIGN KEY (recipe_id) REFERENCES recipes(id) not valid;

alter table "public"."planning_recipes" validate constraint "planning_recipes_recipe_id_fkey";

alter table "public"."recipe_ingredients" add constraint "recipe_ingredients_ingredient_id_fkey" FOREIGN KEY (ingredient_id) REFERENCES ingredients(id) not valid;

alter table "public"."recipe_ingredients" validate constraint "recipe_ingredients_ingredient_id_fkey";

alter table "public"."recipe_ingredients" add constraint "recipe_ingredients_recipe_id_fkey" FOREIGN KEY (recipe_id) REFERENCES recipes(id) not valid;

alter table "public"."recipe_ingredients" validate constraint "recipe_ingredients_recipe_id_fkey";

grant delete on table "public"."ingredient_available_units" to "anon";

grant insert on table "public"."ingredient_available_units" to "anon";

grant references on table "public"."ingredient_available_units" to "anon";

grant select on table "public"."ingredient_available_units" to "anon";

grant trigger on table "public"."ingredient_available_units" to "anon";

grant truncate on table "public"."ingredient_available_units" to "anon";

grant update on table "public"."ingredient_available_units" to "anon";

grant delete on table "public"."ingredient_available_units" to "authenticated";

grant insert on table "public"."ingredient_available_units" to "authenticated";

grant references on table "public"."ingredient_available_units" to "authenticated";

grant select on table "public"."ingredient_available_units" to "authenticated";

grant trigger on table "public"."ingredient_available_units" to "authenticated";

grant truncate on table "public"."ingredient_available_units" to "authenticated";

grant update on table "public"."ingredient_available_units" to "authenticated";

grant delete on table "public"."ingredient_available_units" to "service_role";

grant insert on table "public"."ingredient_available_units" to "service_role";

grant references on table "public"."ingredient_available_units" to "service_role";

grant select on table "public"."ingredient_available_units" to "service_role";

grant trigger on table "public"."ingredient_available_units" to "service_role";

grant truncate on table "public"."ingredient_available_units" to "service_role";

grant update on table "public"."ingredient_available_units" to "service_role";

grant delete on table "public"."ingredients" to "anon";

grant insert on table "public"."ingredients" to "anon";

grant references on table "public"."ingredients" to "anon";

grant select on table "public"."ingredients" to "anon";

grant trigger on table "public"."ingredients" to "anon";

grant truncate on table "public"."ingredients" to "anon";

grant update on table "public"."ingredients" to "anon";

grant delete on table "public"."ingredients" to "authenticated";

grant insert on table "public"."ingredients" to "authenticated";

grant references on table "public"."ingredients" to "authenticated";

grant select on table "public"."ingredients" to "authenticated";

grant trigger on table "public"."ingredients" to "authenticated";

grant truncate on table "public"."ingredients" to "authenticated";

grant update on table "public"."ingredients" to "authenticated";

grant delete on table "public"."ingredients" to "service_role";

grant insert on table "public"."ingredients" to "service_role";

grant references on table "public"."ingredients" to "service_role";

grant select on table "public"."ingredients" to "service_role";

grant trigger on table "public"."ingredients" to "service_role";

grant truncate on table "public"."ingredients" to "service_role";

grant update on table "public"."ingredients" to "service_role";

grant delete on table "public"."instructions" to "anon";

grant insert on table "public"."instructions" to "anon";

grant references on table "public"."instructions" to "anon";

grant select on table "public"."instructions" to "anon";

grant trigger on table "public"."instructions" to "anon";

grant truncate on table "public"."instructions" to "anon";

grant update on table "public"."instructions" to "anon";

grant delete on table "public"."instructions" to "authenticated";

grant insert on table "public"."instructions" to "authenticated";

grant references on table "public"."instructions" to "authenticated";

grant select on table "public"."instructions" to "authenticated";

grant trigger on table "public"."instructions" to "authenticated";

grant truncate on table "public"."instructions" to "authenticated";

grant update on table "public"."instructions" to "authenticated";

grant delete on table "public"."instructions" to "service_role";

grant insert on table "public"."instructions" to "service_role";

grant references on table "public"."instructions" to "service_role";

grant select on table "public"."instructions" to "service_role";

grant trigger on table "public"."instructions" to "service_role";

grant truncate on table "public"."instructions" to "service_role";

grant update on table "public"."instructions" to "service_role";

grant delete on table "public"."planning_ingredients_in_stock" to "anon";

grant insert on table "public"."planning_ingredients_in_stock" to "anon";

grant references on table "public"."planning_ingredients_in_stock" to "anon";

grant select on table "public"."planning_ingredients_in_stock" to "anon";

grant trigger on table "public"."planning_ingredients_in_stock" to "anon";

grant truncate on table "public"."planning_ingredients_in_stock" to "anon";

grant update on table "public"."planning_ingredients_in_stock" to "anon";

grant delete on table "public"."planning_ingredients_in_stock" to "authenticated";

grant insert on table "public"."planning_ingredients_in_stock" to "authenticated";

grant references on table "public"."planning_ingredients_in_stock" to "authenticated";

grant select on table "public"."planning_ingredients_in_stock" to "authenticated";

grant trigger on table "public"."planning_ingredients_in_stock" to "authenticated";

grant truncate on table "public"."planning_ingredients_in_stock" to "authenticated";

grant update on table "public"."planning_ingredients_in_stock" to "authenticated";

grant delete on table "public"."planning_ingredients_in_stock" to "service_role";

grant insert on table "public"."planning_ingredients_in_stock" to "service_role";

grant references on table "public"."planning_ingredients_in_stock" to "service_role";

grant select on table "public"."planning_ingredients_in_stock" to "service_role";

grant trigger on table "public"."planning_ingredients_in_stock" to "service_role";

grant truncate on table "public"."planning_ingredients_in_stock" to "service_role";

grant update on table "public"."planning_ingredients_in_stock" to "service_role";

grant delete on table "public"."planning_ingredients_obtained" to "anon";

grant insert on table "public"."planning_ingredients_obtained" to "anon";

grant references on table "public"."planning_ingredients_obtained" to "anon";

grant select on table "public"."planning_ingredients_obtained" to "anon";

grant trigger on table "public"."planning_ingredients_obtained" to "anon";

grant truncate on table "public"."planning_ingredients_obtained" to "anon";

grant update on table "public"."planning_ingredients_obtained" to "anon";

grant delete on table "public"."planning_ingredients_obtained" to "authenticated";

grant insert on table "public"."planning_ingredients_obtained" to "authenticated";

grant references on table "public"."planning_ingredients_obtained" to "authenticated";

grant select on table "public"."planning_ingredients_obtained" to "authenticated";

grant trigger on table "public"."planning_ingredients_obtained" to "authenticated";

grant truncate on table "public"."planning_ingredients_obtained" to "authenticated";

grant update on table "public"."planning_ingredients_obtained" to "authenticated";

grant delete on table "public"."planning_ingredients_obtained" to "service_role";

grant insert on table "public"."planning_ingredients_obtained" to "service_role";

grant references on table "public"."planning_ingredients_obtained" to "service_role";

grant select on table "public"."planning_ingredients_obtained" to "service_role";

grant trigger on table "public"."planning_ingredients_obtained" to "service_role";

grant truncate on table "public"."planning_ingredients_obtained" to "service_role";

grant update on table "public"."planning_ingredients_obtained" to "service_role";

grant delete on table "public"."planning_recipes" to "anon";

grant insert on table "public"."planning_recipes" to "anon";

grant references on table "public"."planning_recipes" to "anon";

grant select on table "public"."planning_recipes" to "anon";

grant trigger on table "public"."planning_recipes" to "anon";

grant truncate on table "public"."planning_recipes" to "anon";

grant update on table "public"."planning_recipes" to "anon";

grant delete on table "public"."planning_recipes" to "authenticated";

grant insert on table "public"."planning_recipes" to "authenticated";

grant references on table "public"."planning_recipes" to "authenticated";

grant select on table "public"."planning_recipes" to "authenticated";

grant trigger on table "public"."planning_recipes" to "authenticated";

grant truncate on table "public"."planning_recipes" to "authenticated";

grant update on table "public"."planning_recipes" to "authenticated";

grant delete on table "public"."planning_recipes" to "service_role";

grant insert on table "public"."planning_recipes" to "service_role";

grant references on table "public"."planning_recipes" to "service_role";

grant select on table "public"."planning_recipes" to "service_role";

grant trigger on table "public"."planning_recipes" to "service_role";

grant truncate on table "public"."planning_recipes" to "service_role";

grant update on table "public"."planning_recipes" to "service_role";

grant delete on table "public"."plannings" to "anon";

grant insert on table "public"."plannings" to "anon";

grant references on table "public"."plannings" to "anon";

grant select on table "public"."plannings" to "anon";

grant trigger on table "public"."plannings" to "anon";

grant truncate on table "public"."plannings" to "anon";

grant update on table "public"."plannings" to "anon";

grant delete on table "public"."plannings" to "authenticated";

grant insert on table "public"."plannings" to "authenticated";

grant references on table "public"."plannings" to "authenticated";

grant select on table "public"."plannings" to "authenticated";

grant trigger on table "public"."plannings" to "authenticated";

grant truncate on table "public"."plannings" to "authenticated";

grant update on table "public"."plannings" to "authenticated";

grant delete on table "public"."plannings" to "service_role";

grant insert on table "public"."plannings" to "service_role";

grant references on table "public"."plannings" to "service_role";

grant select on table "public"."plannings" to "service_role";

grant trigger on table "public"."plannings" to "service_role";

grant truncate on table "public"."plannings" to "service_role";

grant update on table "public"."plannings" to "service_role";

grant delete on table "public"."recipe_ingredients" to "anon";

grant insert on table "public"."recipe_ingredients" to "anon";

grant references on table "public"."recipe_ingredients" to "anon";

grant select on table "public"."recipe_ingredients" to "anon";

grant trigger on table "public"."recipe_ingredients" to "anon";

grant truncate on table "public"."recipe_ingredients" to "anon";

grant update on table "public"."recipe_ingredients" to "anon";

grant delete on table "public"."recipe_ingredients" to "authenticated";

grant insert on table "public"."recipe_ingredients" to "authenticated";

grant references on table "public"."recipe_ingredients" to "authenticated";

grant select on table "public"."recipe_ingredients" to "authenticated";

grant trigger on table "public"."recipe_ingredients" to "authenticated";

grant truncate on table "public"."recipe_ingredients" to "authenticated";

grant update on table "public"."recipe_ingredients" to "authenticated";

grant delete on table "public"."recipe_ingredients" to "service_role";

grant insert on table "public"."recipe_ingredients" to "service_role";

grant references on table "public"."recipe_ingredients" to "service_role";

grant select on table "public"."recipe_ingredients" to "service_role";

grant trigger on table "public"."recipe_ingredients" to "service_role";

grant truncate on table "public"."recipe_ingredients" to "service_role";

grant update on table "public"."recipe_ingredients" to "service_role";

grant delete on table "public"."recipes" to "anon";

grant insert on table "public"."recipes" to "anon";

grant references on table "public"."recipes" to "anon";

grant select on table "public"."recipes" to "anon";

grant trigger on table "public"."recipes" to "anon";

grant truncate on table "public"."recipes" to "anon";

grant update on table "public"."recipes" to "anon";

grant delete on table "public"."recipes" to "authenticated";

grant insert on table "public"."recipes" to "authenticated";

grant references on table "public"."recipes" to "authenticated";

grant select on table "public"."recipes" to "authenticated";

grant trigger on table "public"."recipes" to "authenticated";

grant truncate on table "public"."recipes" to "authenticated";

grant update on table "public"."recipes" to "authenticated";

grant delete on table "public"."recipes" to "service_role";

grant insert on table "public"."recipes" to "service_role";

grant references on table "public"."recipes" to "service_role";

grant select on table "public"."recipes" to "service_role";

grant trigger on table "public"."recipes" to "service_role";

grant truncate on table "public"."recipes" to "service_role";

grant update on table "public"."recipes" to "service_role";


